import type { GameAchievement, GameAchievementCategory, GameAchievementRarity } from './game-achievements';

export const MINESWEEPER_ACHIEVEMENTS: GameAchievement[] = [
  // ゲームプレイ
  {
    id: 'minesweeper_first_game',
    name: 'はじめの一歩',
    description: '最初のゲームをプレイ',
    icon: '💣',
    category: 'gameplay' as GameAchievementCategory,
    rarity: 'common' as GameAchievementRarity,
    xp: 10,
  },
  {
    id: 'minesweeper_first_clear',
    name: '初クリア',
    description: '初めてゲームをクリア',
    icon: '🎉',
    category: 'gameplay' as GameAchievementCategory,
    rarity: 'common' as GameAchievementRarity,
    xp: 20,
  },
  {
    id: 'minesweeper_10_games',
    name: '地雷探知練習生',
    description: '10回プレイする',
    icon: '📊',
    category: 'milestone' as GameAchievementCategory,
    rarity: 'common' as GameAchievementRarity,
    xp: 25,
  },
  {
    id: 'minesweeper_50_games',
    name: '地雷探知マスター',
    description: '50回プレイする',
    icon: '🎯',
    category: 'milestone' as GameAchievementCategory,
    rarity: 'uncommon' as GameAchievementRarity,
    xp: 50,
  },
  {
    id: 'minesweeper_100_games',
    name: '地雷探知レジェンド',
    description: '100回プレイする',
    icon: '🏆',
    category: 'milestone' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 100,
  },

  // 難易度別クリア
  {
    id: 'minesweeper_beginner_clear',
    name: '初級クリア',
    description: '初級をクリア',
    icon: '🌱',
    category: 'gameplay' as GameAchievementCategory,
    rarity: 'common' as GameAchievementRarity,
    xp: 15,
  },
  {
    id: 'minesweeper_intermediate_clear',
    name: '中級クリア',
    description: '中級をクリア',
    icon: '🌿',
    category: 'gameplay' as GameAchievementCategory,
    rarity: 'uncommon' as GameAchievementRarity,
    xp: 40,
  },
  {
    id: 'minesweeper_expert_clear',
    name: '上級クリア',
    description: '上級をクリア',
    icon: '🌳',
    category: 'gameplay' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 100,
  },

  // タイムアタック（初級）
  {
    id: 'minesweeper_beginner_60s',
    name: '初級スピードスター',
    description: '初級を60秒以内にクリア',
    icon: '⚡',
    category: 'score' as GameAchievementCategory,
    rarity: 'uncommon' as GameAchievementRarity,
    xp: 30,
  },
  {
    id: 'minesweeper_beginner_30s',
    name: '初級ライトニング',
    description: '初級を30秒以内にクリア',
    icon: '🚀',
    category: 'score' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 75,
  },
  {
    id: 'minesweeper_beginner_15s',
    name: '初級神速',
    description: '初級を15秒以内にクリア',
    icon: '👑',
    category: 'score' as GameAchievementCategory,
    rarity: 'epic' as GameAchievementRarity,
    xp: 150,
  },

  // タイムアタック（中級）
  {
    id: 'minesweeper_intermediate_180s',
    name: '中級スピードスター',
    description: '中級を3分以内にクリア',
    icon: '⏱️',
    category: 'score' as GameAchievementCategory,
    rarity: 'uncommon' as GameAchievementRarity,
    xp: 40,
  },
  {
    id: 'minesweeper_intermediate_90s',
    name: '中級ライトニング',
    description: '中級を90秒以内にクリア',
    icon: '💨',
    category: 'score' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 100,
  },
  {
    id: 'minesweeper_intermediate_60s',
    name: '中級神速',
    description: '中級を60秒以内にクリア',
    icon: '🔥',
    category: 'score' as GameAchievementCategory,
    rarity: 'epic' as GameAchievementRarity,
    xp: 200,
  },

  // タイムアタック（上級）
  {
    id: 'minesweeper_expert_300s',
    name: '上級スピードスター',
    description: '上級を5分以内にクリア',
    icon: '🎖️',
    category: 'score' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 100,
  },
  {
    id: 'minesweeper_expert_180s',
    name: '上級ライトニング',
    description: '上級を3分以内にクリア',
    icon: '💎',
    category: 'score' as GameAchievementCategory,
    rarity: 'epic' as GameAchievementRarity,
    xp: 200,
  },
  {
    id: 'minesweeper_expert_120s',
    name: '上級神速',
    description: '上級を2分以内にクリア',
    icon: '🏅',
    category: 'score' as GameAchievementCategory,
    rarity: 'legendary' as GameAchievementRarity,
    xp: 500,
  },

  // 特殊実績
  {
    id: 'minesweeper_no_flag',
    name: 'ノーフラグ',
    description: 'フラグを使わずにクリア',
    icon: '🚫',
    category: 'special' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 75,
  },
  {
    id: 'minesweeper_perfect_flag',
    name: 'パーフェクトフラグ',
    description: '地雷のみにフラグを立ててクリア（誤フラグなし）',
    icon: '🎯',
    category: 'special' as GameAchievementCategory,
    rarity: 'uncommon' as GameAchievementRarity,
    xp: 50,
  },
  {
    id: 'minesweeper_first_click_safe',
    name: 'ラッキースタート',
    description: '最初のクリックで大きく開く（8セル以上）',
    icon: '🍀',
    category: 'special' as GameAchievementCategory,
    rarity: 'common' as GameAchievementRarity,
    xp: 15,
  },

  // 連続クリア
  {
    id: 'minesweeper_streak_3',
    name: '3連勝',
    description: '3回連続でクリア',
    icon: '🔥',
    category: 'milestone' as GameAchievementCategory,
    rarity: 'uncommon' as GameAchievementRarity,
    xp: 40,
  },
  {
    id: 'minesweeper_streak_5',
    name: '5連勝',
    description: '5回連続でクリア',
    icon: '🌟',
    category: 'milestone' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 100,
  },
  {
    id: 'minesweeper_streak_10',
    name: '10連勝',
    description: '10回連続でクリア',
    icon: '✨',
    category: 'milestone' as GameAchievementCategory,
    rarity: 'epic' as GameAchievementRarity,
    xp: 200,
  },

  // 対戦実績
  {
    id: 'minesweeper_battle_first_win',
    name: '初勝利',
    description: 'オンライン対戦で初勝利',
    icon: '⚔️',
    category: 'gameplay' as GameAchievementCategory,
    rarity: 'uncommon' as GameAchievementRarity,
    xp: 50,
  },
  {
    id: 'minesweeper_battle_10_wins',
    name: 'バトルマスター',
    description: 'オンライン対戦で10勝',
    icon: '🏆',
    category: 'milestone' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 100,
  },
  {
    id: 'minesweeper_battle_comeback',
    name: '逆転勝利',
    description: '相手より進捗が遅れていた状態から逆転勝利',
    icon: '🔄',
    category: 'special' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 75,
  },
  {
    id: 'minesweeper_battle_perfect',
    name: 'パーフェクトバトル',
    description: '相手が地雷を踏む前にクリアして勝利',
    icon: '💯',
    category: 'special' as GameAchievementCategory,
    rarity: 'epic' as GameAchievementRarity,
    xp: 150,
  },

  // 隠し実績
  {
    id: 'minesweeper_night_owl',
    name: '夜更かしマインスイーパー',
    description: '深夜2時〜5時にプレイ',
    icon: '🦉',
    category: 'special' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 75,
    hidden: true,
    hint: '夜更かしする地雷探知兵...',
  },
  {
    id: 'minesweeper_lucky_guess',
    name: 'ラッキーゲス',
    description: '50%の確率を5回連続で当てる',
    icon: '🎲',
    category: 'special' as GameAchievementCategory,
    rarity: 'epic' as GameAchievementRarity,
    xp: 150,
    hidden: true,
    hint: '運も実力のうち...',
  },
  {
    id: 'minesweeper_all_difficulties',
    name: 'マスターオブマインズ',
    description: '全難易度をクリア',
    icon: '🎓',
    category: 'milestone' as GameAchievementCategory,
    rarity: 'rare' as GameAchievementRarity,
    xp: 100,
    hidden: true,
    hint: '全ての難易度を制覇せよ...',
  },
];

export const MINESWEEPER_ACHIEVEMENT_TOTAL = MINESWEEPER_ACHIEVEMENTS.length;
